import Vue from "@vitejs/plugin-vue";
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { URL, fileURLToPath } from "node:url";
import UnoCSS from "unocss/vite";
import Fonts from "unplugin-fonts/vite";
import Components from "unplugin-vue-components/vite";
import { type Plugin, defineConfig } from "vite";
import Vuetify, { transformAssetUrls } from "vite-plugin-vuetify";

type GitVersionOutput = {
  FullSemVer?: string;
  InformationalVersion?: string;
  Sha?: string;
  BranchName?: string;
};

function generateGitVersionModule(): void {
  const output = execFileSync("gitversion", ["/output", "json"], {
    encoding: "utf8",
  });

  const parsed = JSON.parse(output) as GitVersionOutput;
  const fullSemVer = parsed.FullSemVer ?? "0.0.0-local";
  const informationalVersion =
    parsed.InformationalVersion ?? "0.0.0-local+0000000";
  const sha = parsed.Sha ?? "0000000000000000000000000000000000000000";
  const branchName = parsed.BranchName ?? "local";

  const generatedDirectory = path.resolve(__dirname, "src/generated");
  const generatedFile = path.join(generatedDirectory, "gitversion.ts");
  mkdirSync(generatedDirectory, { recursive: true });

  const source =
    "// This file is generated by Vite (gitversion plugin). Do not edit manually.\n" +
    "export interface GitVersionInfo {\n" +
    "  fullSemVer: string;\n" +
    "  informationalVersion: string;\n" +
    "  sha: string;\n" +
    "  branchName: string;\n" +
    "}\n\n" +
    "export const gitVersion: GitVersionInfo = {\n" +
    `  fullSemVer: ${JSON.stringify(fullSemVer)},\n` +
    `  informationalVersion: ${JSON.stringify(informationalVersion)},\n` +
    `  sha: ${JSON.stringify(sha)},\n` +
    `  branchName: ${JSON.stringify(branchName)},\n` +
    "};\n";

  writeFileSync(generatedFile, source, "utf8");
}

function gitVersionModulePlugin(): Plugin {
  return {
    name: "gitversion-module-generator",
    enforce: "pre",
    buildStart() {
      generateGitVersionModule();
    },
    configureServer() {
      generateGitVersionModule();
    },
  };
}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    gitVersionModulePlugin(),
    Vue({
      template: { transformAssetUrls },
    }),
    // https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin#readme
    Vuetify({
      autoImport: true,
      styles: {
        configFile: "src/styles/settings.scss",
      },
    }),
    Components({
      dts: "src/components.d.ts",
    }),
    Fonts({
      fontsource: {
        families: [
          {
            name: "Roboto",
            weights: [100, 300, 400, 500, 700, 900],
            styles: ["normal", "italic"],
          },
        ],
      },
    }),
    UnoCSS(),
  ],
  optimizeDeps: {
    exclude: ["vuetify", "vue-router"],
  },
  define: { "process.env": {} },
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
    extensions: [".js", ".json", ".jsx", ".mjs", ".ts", ".tsx", ".vue"],
  },
  server: {
    port: 3000,
  },
});
