/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavigation: typeof import('./components/app-navigation.vue')['default']
    AppNavigationItem: typeof import('./components/app-navigation-item.vue')['default']
    AppTitlebar: typeof import('./components/app-titlebar.vue')['default']
    DayPageContent: typeof import('./components/day-page-content.vue')['default']
    ExternalRefCard: typeof import('./components/cards/external-ref-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeacherAccessDialog: typeof import('./components/teacher-access-dialog.vue')['default']
  }
}
