/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/nds-web-engineering/': RouteRecordInfo<'/nds-web-engineering/', '/nds-web-engineering', Record<never, never>, Record<never, never>>,
    '/nds-web-engineering/day-1': RouteRecordInfo<'/nds-web-engineering/day-1', '/nds-web-engineering/day-1', Record<never, never>, Record<never, never>>,
    '/nds-web-engineering/day-2': RouteRecordInfo<'/nds-web-engineering/day-2', '/nds-web-engineering/day-2', Record<never, never>, Record<never, never>>,
    '/nds-web-engineering/day-3': RouteRecordInfo<'/nds-web-engineering/day-3', '/nds-web-engineering/day-3', Record<never, never>, Record<never, never>>,
    '/nds-web-engineering/day-4': RouteRecordInfo<'/nds-web-engineering/day-4', '/nds-web-engineering/day-4', Record<never, never>, Record<never, never>>,
    '/nds-web-engineering/day-5': RouteRecordInfo<'/nds-web-engineering/day-5', '/nds-web-engineering/day-5', Record<never, never>, Record<never, never>>,
    '/nds-web-engineering/day-6': RouteRecordInfo<'/nds-web-engineering/day-6', '/nds-web-engineering/day-6', Record<never, never>, Record<never, never>>,
    '/nds-web-engineering/day-7': RouteRecordInfo<'/nds-web-engineering/day-7', '/nds-web-engineering/day-7', Record<never, never>, Record<never, never>>,
  }
}
